<<<<<<< HEAD
govuk_breadcrumb: 0
search_box: 0
govuk_cookie: 0
govuk_phase_banner: ''
phase_banner_message:
  value: "<p>This is a new service – your <a class=\"govuk-link\" href=\"/contact/feedback\">feedback</a> will help us to improve it.</p>\r\n"
  format: full_html
_core:
  default_config_hash: nS-G7Is2pUbuItsDst0AbnICh25x6m3ID0MmgM0mkrc
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 1
||||||| e981d1352
=======
govuk_breadcrumb: 1
search_box: 1
govuk_cookie: 1
govuk_phase_banner: alpha
phase_banner_message:
  format: full_html
  value: 'This is a new service – your <a class="govuk-link" href="/contact/feedback">feedback</a> will help us to improve it.'
_core:
  default_config_hash: nS-G7Is2pUbuItsDst0AbnICh25x6m3ID0MmgM0mkrc
>>>>>>> 5960f75509be2bad4ce7d76019c45ffdc7582004
