govuk_breadcrumb: 0
search_box: 0
govuk_cookie: 0
govuk_phase_banner: ''
phase_banner_message:
  value: "<p>This is a new service – your <a class=\"govuk-link\" href=\"/contact/feedback\">feedback</a> will help us to improve it.</p>\r\n"
  format: full_html
_core:
  default_config_hash: nS-G7Is2pUbuItsDst0AbnICh25x6m3ID0MmgM0mkrc
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 1
